creation_rules:
- path: secrets/params.yaml
  encrypted_regex: '^(password|api-key|default_password)'
  pgp: 905EBD494A6AA2B774ED5C67621620CDA290611D
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 62B45B1C340BD6D6500A61A2F0CE635FB7CB6FE2
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 62B45B1C340BD6D6500A61A2F0CE635FB7CB6FE2
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
