apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata: 
  name: fluxcd-gitops-cluster
spec: 
  kubernetes: 
    version: "1.25.x"
  flannel: 
    version: "0.20.x"
  contour: 
    version: "1.23.x"
  prometheus: 
    version: "0.60.x"
  registry: 
    version: "2.8.x"
  containerd: 
    version: "1.6.x"
  ekco: 
    version: "latest"
  minio: 
    version: "2022-10-20T00-55-09Z"
  openebs: 
    version: "3.3.x"
    isLocalPVEnabled: true
    localPVStorageClassName: "default"
  certManager: 
    version: "1.9.x"

