#@data/values
hostname: node
domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:swTKkmFEVINjQUw16tAbmXJPeAZxDyf6bQ==,iv:LvUfeaUPixvpqzm8mAtI5esEw6RTy6Js2sLj/Ane4Tw=,tag:lSvabDfgPlLJ7f2e5KKv8w==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:17 600 602
node:
    cpus: 4
    memory: 8192
    disk_size: 52
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:j0ZlkBiUIzts1qqQCAsnq1Ob2A==,iv:L4aP1quvMmYQk6r19yFxgoD8jQ4qokD4HzZ51vecnJ0=,tag:F4mA4bOsuMKtgkTCHMcKgg==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources
    network: kurl-pg
    datastore: vsanDatastore
    folder: replicated
cloudflare:
    api-key: ENC[AES256_GCM,data:GD6XvKyASsw7GQTZszhOgVhjbVMQtVNEJQzSv1zLQshz4Mazlw==,iv:QB0zXOi50b6cV3dsmvmI4zJTyl4qWMxihEQe5LGX7oI=,tag:YzoWcF1o3goEDCf5H5m3yg==,type:str]
git:
    gpg-key: 9461DC21724F05B0A93965D66B744289530BDD93
    owner: shortrib-labs
    repository: fluxcd-lab
    path: clusters
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-17T18:47:43Z"
    mac: ENC[AES256_GCM,data:KW/+Z7ecsHhOEMUOqQntTR3IZmKubt70+u99x6bdWNVqNmlwQgaJWAiKgtUDioyppbK0e50dwd8XNZNHYL34tIWQYeaCMx36erh4ltYf8jYug+ylh9JsNETu29RRFfRG/q8sd3sMWGPMiCkPyZn4DYTVsPAGJoGnUVTJn2b7Dcs=,iv:l35uIf1PVeFE0B/tDTkMsefeR+z1Z9uXgXvaZ+tIb0o=,tag:LEwMO/ZYcaSf7Of41ZjBCw==,type:str]
    pgp:
        - created_at: "2022-11-17T16:08:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAKiA25VKQ44VJdKLwXsyHFw9daBJPBYJsGuP+HMA+1Dww
            hEJUudCl2ureThbWSzpnj5MiseAxfMUe4S+foWVgugVQAm7ge1XG0jXmoT8NUI2E
            1GYBCQIQZx5QI0d8HHO0CNfAl8ZkJYqdMTMjuLX9xgJlha9yKFMBIaJZGEG07VPR
            B5/gQ75CMraiQ4xulhBcNwjmgVg/NSEM245epKvjSHlDZ0JUSum5ABjuBLrmGOU2
            cyQj8E1DOmw=
            =uHk4
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)
    version: 3.7.3
